### ISSUE TITLE
Ability to change flavor text in the advanced editor

### ISSUE THREAD

**Issue by ThatOneCalculator** [mosparo/mosparo#128]
I really love all the customization provided, but one thing that would be nice is the ability to change the flavor text for the captcha. "I accept that the form entries are checked for spam and stored encrypted for 14 days" is a bit too verbose IMO, and I'd personally like to change it to something simple like "Are you a robot?"

**Comment by zepich** [comment]
Hi @ThatOneCalculator 

Thank you very much for your message.

You can do that already (in general)... :)

It's not possible directly in mosparo in the interface (there is an [idea](https://github.com/orgs/mosparo/discussions/40) for the future to add such an interface in the UI) - but you can adjust the visible texts in the frontend/integration. 

## Custom integration

When you integrate it directly with the script (custom integration), you can set the frontend texts in the initialization options (see [`customMessages`](https://documentation.mosparo.io/docs/integration/custom#additional-options)).

## WordPress integration

If you're using the WordPress integration, you can use a filter to adjust the text. Filter: https://github.com/mosparo/wordpress-plugin/blob/master/src/MosparoIntegration/Helper/FrontendHelper.php#L111

### Example
```php
function mosparoOverrideMessages($options)
{
    $options['customMessages'] = [
        'de' => [
            'label' => 'Ich akzeptiere',
        ],
        'en' => [
            'label' => 'I accept',
        ],
    ];

    return $options;
}
add_filter('mosparo_integration_filter_frontend_options', 'mosparoOverrideMessages');
```

## Other integration

The other integrations are not yet prepared for the adjustment in your code. Can you tell me which integration you use so we can prioritize it?

## V1.0

With V1.0, we add an invisible mode, with which no checkbox is visible, and therefore the very long sentence is not visible at all. That's maybe interesting for you.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @ThatOneCalculator 

Okidoki, so you're building your custom integration by using the JavaScript API client for the verification process.

You can adjust the texts in the initialization of the mosparo box (like described here: https://documentation.mosparo.io/docs/integration/custom#additional-options)

Please let me know if you need any help!

Kind regards,

zepich

**Comment by ThatOneCalculator** [comment]
Gotcha, thank you! I'll close this for now since there is custom text support. I'll be working on this throughout the next week or so.
