### ISSUE TITLE
Shared links to the submission are redirected to the project list

### ISSUE THREAD

**Issue by Digi92** [mosparo/mosparo#130]
Hello,

i was about to show a submission to a colleague to talk about a filter adjustment, and I noticed that the link to the submission redirected my colleague to the projects overview (project_list) .
Only after he had selected the corresponding project he was able to open the link to the submission.

Steps to reproduce it:
1. log in and open a submission from a project. 
2. copy the link (should be this one (https://captcha.test.de/submissions/225/view)
3. log out and log in again
4. now try to call the copied link without first calling the project dashboard.
If we want the link to work we have to open the project dashboard first.

It seems that the ProjectSubscriber redirects us with the condition "`if ($activeProject === null || (!$this->security->isGranted('ROLE_ADMIN') && !$activeProject->isProjectMember($this->security->getUser()))) {`", because we have not yet selected the project when we logged in and the variable "$activeProject" has the value "null".
Github File: [https://github.com/mosparo/mosparo/blob/master/src/Subscriber/ProjectSubscriber.php#L136](https://github.com/mosparo/mosparo/blob/master/src/Subscriber/ProjectSubscriber.php#L136)

I had expected that as long as I have access to the project and its submissions as a user, I would be able to see the submission without having to go to the dashboard first.

Tested under version 0.4.5

**Comment by zepich** [comment]
Hi @Digi92

Thank you very much for reporting this issue.

I've tested it and added a fix for this problem, at least for the view and edit routes (not the delete ones).

I've just released v0.4.6, which contains this fix.

Thank you very much for your help!

Kind regards,

zepich
