### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by mpaglia0** [mosparo/mosparo#169]
Hi all,
I have integrated manually mosparo in my test website.
When entering the contact form page the Javascript returns this error:
**Cannot find the mosparo container.**
But in the contact form page the empty `<div>` with the ID of the mosparo box is present and same ID is correctly listed as option in the Javascript parameters.

**Comment by zepich** [comment]
Hi @mpaglia0 

How did you specify the ID? Have you put an '#' sign in front of it? If yes, please remove that one and try it again.

If you have no '#' in front of the ID, can you try this in the browser JavaScript console?

```javascript
document.getElementById('your-id')
```

The result of this should be the HTML code of the container and not `null`.

Kind regards,

zepich

**Comment by mpaglia0** [comment]
Ciao @zepich 
I put any '#' or other symbol in front of the ID but if I enter your string in the browser consolre the result is `null`.

**Comment by zepich** [comment]
Hi @mpaglia0 

Can you share your code?

1. The HTML code with the mosparo container
2. The JavaScript code for the initialization

**Comment by mpaglia0** [comment]
`<script src="https://www.mosparo.mauriziopaglia.it/public/build/mosparo-frontend.js" defer></script>
<script>
    var m;
    window.onload = function(){
        m = new mosparo(
               '[mosparo_spambox]',
               '[www.mosparo.mauriziopaglia.it]',
               '[f37134f6-7b19-4a25-bac9-0783110aaa85]',
               '[lwEKO4E54VkmFpV5K-y8mSCRGVPAAcmB2C5Uuy-XZMU]'
        );
    };
</script>`

**Comment by mpaglia0** [comment]
Seems cannot enter correctly indentation...

**Comment by mpaglia0** [comment]
Anyway... this is the script I put at the bottom of each website page

**Comment by mpaglia0** [comment]
<div id="mosparo_spambox"></div>

**Comment by mpaglia0** [comment]
And this is the empty `div` I entered in my contact form page

**Comment by zepich** [comment]
Perfect, thank you very much.

The problem are the `[` and `]`. I've added them in the demo code to show it is a placeholder. You have to remove them.

```html
<script> var m; window.onload = function(){ m = new mosparo( 'mosparo_spambox', 'www.mosparo.mauriziopaglia.it', 'f37134f6-7b19-4a25-bac9-0783110aaa85', 'lwEKO4E54VkmFpV5K-y8mSCRGVPAAcmB2C5Uuy-XZMU' ); }; </script>
```

**Comment by mpaglia0** [comment]
Aha!!
It simply works now...
Please apologize for my very stupid questions but I am not a technician.

Thanks,
Maurizio

**Comment by zepich** [comment]
Hi @mpaglia0 

That's no problem! I'm happy I can help you, and it's working now! :)

Please let me know if you have any other questions.

Kind regards,

zepich

**Comment by mpaglia0** [comment]
Thank you very much!
