### ISSUE TITLE
CORS and CSP

### ISSUE THREAD

**Issue by mpaglia0** [mosparo/mosparo#261]
I have an error in my mosparo box (No submit token available. Validation of this form is not possible).
Looking in Firefox console I see this error: Ensure CORS response header values are valid.
Searching on Google I entered in my .htaccess file the following instruction:
`<IfModule mod_headers.c>
   Header set Access-Control_Allow-Origin "mosparo_pah_on_my_website"
</IfModule>`
But it does not work...

**Comment by zepich** [comment]
Hi @mpaglia0 

Thank you very much for your question.

Can you verify that your website's domain is correctly configured in your project's `Hosts` settings in mosparo? You should only configure the domain without protocol (like `https://`) and path (like `/contact-form`).

![image](https://github.com/user-attachments/assets/ffd24e39-bc6b-45f2-92ee-5eb0b2a00899)

This setting sets the correct CORS header on the mosparo side, so you should not have trouble including mosparo on your website.

Kind regards,

zepich

**Comment by mpaglia0** [comment]
Yes, it works!
thanks

**Comment by zepich** [comment]
Hi @mpaglia0 

Perfect, thank you very much for letting me know!

Have a nice day!

Kind regards,

zepich
