### ISSUE TITLE
Submissions for 2nd project not appearing under Dashboard or Submissions tabs, but they are appearing in database.

### ISSUE THREAD

**Issue by Geremia** [mosparo/mosparo#263]
I created a new project (it has project ID 3) for a different website, and submissions aren't appearing under the "Submissions" or "Dashboard" tabs. The submit tokens are appearing in the `submit_token` table, and submissions are appearing in the `submissions` table. I run
```bash
php bin/console mosparo:cleanup-database
php bin/console mosparo:rulesets:refresh
php bin/console mosparo:geoip2:download-database
```
regularly, too.

I don't get this issue for my 1<sup>st</sup> project (with project ID 1), though.

**Comment by zepich** [comment]
Hi @Geremia

Thank you very much for your issue.

I guess the submission was not verified by the backend of your website (project ID 3) via the mosparo verification API.

If you have a look in the `submission` table, can you check if the column `valid` is not `NULL`? After the verification, the column `valid` will contain either a `1` or `0` and should no longer be `NULL`.

In the submissions list, you'll see only submissions for which the `valid` column is not `NULL`.

Can you verify whether the `valid` column in the `submission` table contains either a `0` or a `1`?

Kind regards,

zepich

**Comment by Geremia** [comment]
@zepich 

> I guess the submission was not verified by the backend of your website (project ID 3) via the mosparo verification API.

> In the submissions list, you'll see only submissions for which the `valid` column is not `NULL`.

It is `NULL`…

The issue was I had tho wrong `$projectPublicKey` set in my `verify.php` script.

Thanks!
