### ISSUE TITLE
Session handling for support multi-server setups

### ISSUE THREAD

**Issue by Digi92** [mosparo/mosparo#27]
Hi,

i noticed that Mosparo uses the default Symfony sessions handling, which does not work when the application is served from multiple servers.

Symfony Session Dokumentation: [Symfony stores sessions in files by default. If your application is served by multiple servers, you'll need to use a database instead to make sessions work across different servers.](https://symfony.com/doc/5.4/session.html#store-sessions-in-a-database)

For this reason I have created a pull request that contains all the necessary changes to switch to database session handling: https://github.com/mosparo/mosparo/pull/26

**Comment by zepich** [comment]
Hi @Digi92

Thank you very much for your work!

As written in the pull request: I've adjusted the changes and merged them into the repo.

We will release a new version (v0.3.9) tomorrow with your changes included.

Thank you very much!

Kind regards,

zepich
