### ISSUE TITLE
Suggestion: Add .nvmrc to support NVM for frontend building

### ISSUE THREAD

**Issue by Digi92** [mosparo/mosparo#34]
Hi,
i noticed that neither in the documentation or in the code the required node version for building the frontend is noted.
Could you add this information.
Additionally it would be good to create a `.nvmrc` file.
Documentation: [https://github.com/nvm-sh/nvm#nvmrc](https://github.com/nvm-sh/nvm#nvmrc)

**Comment by zepich** [comment]
Hi @Digi92 

Thank you very much for your hint. We will add the information in the documentation and README. Right now, we use version 16 for the build.

We will also have a look at the `.nvmrc` file. 

I will leave this issue open until we've done that.

**Comment by zepich** [comment]
Hi @Digi92 

We've adjusted the documentation, the README.md, and added the .nvmrc file as suggested by you. We've also updated to Node.js 18.

Thank you very much for your input!

Kind regards,

zepich
