### ISSUE TITLE
Return character in ip allow list field generating an error

### ISSUE THREAD

**Issue by Digi92** [mosparo/mosparo#56]
Hello, 
while testing the option "IP allow list".
I noticed that if there are one or more "return character (\r)" in the string, it comes to errors in "SecurityHelper->isIpOnAllowList".
This leads to the fact that Captcha cannot be loaded in the form.
In order to fix this I have replaced `explode(PHP_EOL, $ipAllowList)` with `preg_split('/\r\n|\r|\n/', $ipAllowList)`
replaced. 
See explanation why: [https://stackoverflow.com/a/29471912](https://stackoverflow.com/a/29471912)

Additionally it was not considered that `Factory::parseAddressString` and `Subnet::parseString` can return a "null" value.

My initial error: 
```
Uncaught Error: Call to a member function getAddressType() on null {"exception":"[object] (Error(code: 0): Call to a member function getAddressType() on null at /var/www/htdocs/src/Helper/SecurityHelper.php:71)"} []
```

For this reason I have created a pull request that contains all the necessary changes: #55

**Comment by zepich** [comment]
Hi @Digi92 

Awesome! Thank you very much for reporting this issue and providing the pull request.

The changes make absolute sense and are perfect.

I merged the pull request, and we will release a new version in the following days.

Kind regards,

zepich
