### ISSUE TITLE
Wizard configuration database error 500

### ISSUE THREAD

**Issue by Silbad** [mosparo/mosparo#63]
Hello,
On Ubuntu 22.04 + LAMP with PHP 8.2 & Mosparo 0.3.18
On wizard's step database configuration, I have an error 500 after submit form.
In logs : 
`php.CRITICAL: Uncaught Error: Undefined constant "XML_PI_NODE" {"exception":"[object] (Error(code: 0): Undefined constant`
Thanks...

**Comment by Silbad** [comment]
Ok I fix this issue : 
`sudo apt install php8.2-xml`
Although I still can't connect to the remote base ^^ but I'll get there

**Comment by zepich** [comment]
Hi @Silbad 

Thank you very much for reporting this issue.

Yes, the `xml` extension is responsible for this issue. It must be added to our list of required extensions and checked in the first step of the setup wizard. We will adjust that.

What is the problem with the remote database? Do you get any error messages?

Kind regards,

zepich

**Comment by Silbad** [comment]
For information I also had to install the **php-dom** extension at the very beginning to access the first wizard window.

I tell you when I found the pb for the remote database ;)

**Comment by Silbad** [comment]
I have CSP issue for the remote database
` EvalError: call to eval() blocked by CSP`

**Comment by Silbad** [comment]
Is this related?
https://github.com/mosparo/mosparo/issues/46

**Comment by zepich** [comment]
Which database (service) do you use?

**Comment by Silbad** [comment]
MySQL : 8.0.33-0ubuntu0.22.04.2

**Comment by zepich** [comment]
The CSP is a frontend feature and is sent with a header to your browser.

The database connection is established in the backend. CSP should not be an issue there. The CSP error sounds more like an issue from your browser (extension?).

Do you see an error in the wizard? Or do you see an error in the log file (var/log/prod*.log)?

**Comment by Silbad** [comment]
You're right it's an extension (vuetool)

"Échec de la connexion à la base de données. Veuillez vérifier les paramètres ci-dessous et réessayer."

and no error in the log file

it must be a problem on my side...

**Comment by zepich** [comment]
Can you connect from the CLI of your server? 

Example: 
```
mysql -h[host] -u[username] -p '[database_name]'
```

**Comment by zepich** [comment]
Do you have special characters in your password? If yes, can you try a password without special characters? Maybe we have an encoding bug with one of the special characters.

**Comment by Silbad** [comment]
Yes it's on my side I have the mistake:
ERROR 2003 (HY000): Can't connect to MySQL server
I'll look into it, thanks

**Comment by Silbad** [comment]
I success to log in, I had forgotten to create a ufw rule... anyway
But, after this I have an error 500

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Log : 
[2023-05-22T19:04:16.874782+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Cannot rename "/tmp/env.mosparo.phpB7rKxh" (...) permission denied

already, at the beginning of the installation, I had to grant certain rights for it to work:
`sudo chown -R www-data:www-data /var/www/mosparo.yourwebsite.com/var/`

**Comment by zepich** [comment]
Glad to hear that it worked!

You should also set the owner of the `config` directory to the `www-data` user:

`sudo chown -R www-data: /var/www/mosparo.mywebsite.com/config/`

I already noticed that we do not check the file write access before starting the setup. So we will add a check in the first step of the wizard with the next major version.

**Comment by Silbad** [comment]
It's alive ! tks

**Comment by zepich** [comment]
Awesome! No problem! :)
