### ISSUE TITLE
The "mosparo:rulesets:refresh" command returns 1 every time

### ISSUE THREAD

**Issue by Digi92** [mosparo/mosparo#71]
Hi,
i just noticed that the console command "mosparo:rulesets:refresh" always returns the return code 1, which implied an error.
This should be at least a 0 and it would be best if this value would set with the constance of the class "Command".

Code: https://github.com/mosparo/mosparo/blob/master/src/Command/RefreshRulesetsCommand.php#L33

**Comment by zepich** [comment]
Hi @Digi92 

Thank you very much for your report.

Yes, you're right. That's not good. I will correct that with the next version.

Kind regards

zepich

**Comment by zepich** [comment]
Fixed with v0.3.20.
